version: '3.7'

services:
  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    image: confluentinc/cp-zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka-broker:
    hostname: kafka-broker
    container_name: kafka-broker
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 500
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

  generator-service:
    container_name: generator-service
    hostname: generator-service
    build:
      context: ./
      dockerfile: src/main/scala/generator_service/Dockerfile
    depends_on:
      - kafka-broker
    environment:
      - KFTI_INPUT_FILE_NAME=data/RC_2010-12
      - KFTI_KAFKA_BROKER_ADDRESS=kafka-broker:9092
    volumes:
      - ./data:/data

  language-service:
    container_name: language-service
    hostname: language-service
    build:
      context: ./
      dockerfile: src/main/scala/language_service/Dockerfile
    depends_on:
      - kafka-broker
      - generator-service
    environment:
      - KFTI_KAFKA_BROKER_ADDRESS=kafka-broker:9092

  sentiment-service:
    container_name: sentiment-service
    hostname: sentiment-service
    build:
      context: ./
      dockerfile: src/main/scala/sentiment_service/Dockerfile
    depends_on:
      - kafka-broker
      - generator-service
    environment:
      - KFTI_KAFKA_BROKER_ADDRESS=kafka-broker:9092

  keyword-service:
    container_name: keyword-service
    hostname: keyword-service
    build:
      context: ./
      dockerfile: src/main/scala/keyword_service/Dockerfile
    depends_on:
      - kafka-broker
      - generator-service
    environment:
      - KFTI_KAFKA_BROKER_ADDRESS=kafka-broker:9092

  statistics-service:
    container_name: statistics-service
    hostname: statistics-service
    build:
      context: ./
      dockerfile: src/main/scala/statistics_service/Dockerfile
    depends_on:
      - kafka-broker
      - generator-service
      - language-service
      - sentiment-service
      - keyword-service
    ports:
      - 1234:1234
    environment:
      - KFTI_KAFKA_BROKER_ADDRESS=kafka-broker:9092

